#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='aarch64-unknown-serenity'
CROSS_COMPILE_SYSTEM='serenityos'
CROSS_COMPILE_ARCHITECTURE='aarch64'

CC="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${SENNA_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
