#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='alpha-unknown-openbsd'
CROSS_COMPILE_SYSTEM='openbsd'
CROSS_COMPILE_ARCHITECTURE='alpha'

CC="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${ATAR_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
