#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='alpha-unknown-netbsd'
CROSS_COMPILE_SYSTEM='netbsd'
CROSS_COMPILE_ARCHITECTURE='alpha'

CC="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${DAKINI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
