#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='arm-remarkable-linux-gnueabihf'
CROSS_COMPILE_SYSTEM='linux'
CROSS_COMPILE_ARCHITECTURE='arm'

CC="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${NAN_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
