#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='arm-cervantes-linux-gnueabi'
CROSS_COMPILE_SYSTEM='linux'
CROSS_COMPILE_ARCHITECTURE='arm'

CC="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${NIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
