#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='arm-obreey-linux-gnueabi'
CROSS_COMPILE_SYSTEM='linux'
CROSS_COMPILE_ARCHITECTURE='arm'

CC="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${NERO_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
