#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='arm-kindle-linux-gnueabi'
CROSS_COMPILE_SYSTEM='linux'
CROSS_COMPILE_ARCHITECTURE='arm'

CC="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${KEL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
