#/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='i386-unknown-linux-gnu'
CROSS_COMPILE_SYSTEM='linux'
CROSS_COMPILE_ARCHITECTURE='i386'

CC="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}2.13-gcc"
CXX="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}2.13-g++"
AR="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${OBGGCC_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
