#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='riscv64-unknown-freebsd15.0'
CROSS_COMPILE_SYSTEM='freebsd'
CROSS_COMPILE_ARCHITECTURE='riscv64'

CC="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${LOKI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
