#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='x86_64-unknown-haiku'
CROSS_COMPILE_SYSTEM='haiku'
CROSS_COMPILE_ARCHITECTURE='x86_64'

CC="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${SIL_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
