#!/bin/bash

set -eu

CROSS_COMPILE_TRIPLET='x86_64-unknown-dragonfly'
CROSS_COMPILE_SYSTEM='dragonfly'
CROSS_COMPILE_ARCHITECTURE='x86_64'

CC="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export CROSS_COMPILE_TRIPLET \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF
